pipeline {
    agent any
    stages {
        stage ('build maven') {
            steps {
                sh 'pwd'
                sh 'mvn clean install package'
            }

        }
        stage ('copy artifacts') {
            steps {
                sh 'pwd'
                sh 'cp -r target/*.jar docker'
            }
        }
        stage ('unit tests') {
            steps {
                sh 'pwd'
                sh 'mvn test'
            }
        }
        stage ('build docker image') {
            steps {
                script {
                    def customImage = docker.build("shoeab14/petclinic:${env.BUILD_NUMBER}", "./docker")
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                    customImage.push()
                }
            }
        }
    }
}