pipeline {
    agent any
    stages {
        stage ('build maven') {
            steps {
                sh 'pwd'
                sh 'mvn clean install package'
            }
        }
        stage ('copy artifacts') {
            steps {
                sh 'pwd'
                sh 'cp -r target/*.jar docker'
            }
        }
        stage ('unit tests') {
            steps {
                sh 'pwd'
                sh "mvn test"
            }
        }
        stage ('build docker image') {
            steps {
                script {
                    def customImage = docker.build("shoeab14/petclinic:${env.BUILD_NUMBER}", "./docker")
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                    customImage.push()
                }
            }
        }
    }
    stage ('build on kubernetes') {
        steps {
            script {
                withKubeConfig={[credentialsId: 'kubeconfig']} {
                    sh 'pwd'
                    sh 'cp -R helm/* .'
                    sh 'ls -ltrh'
                    sh 'pwd'
                    sh '/usr/local/bin/helm upgrade --install petclinic-app petclinic --set image.repository=shoeab14/petclinic --set image.tag=${BUILD_NUMBER}'
                }
            }
        }
    }
}

}